### ISSUE TITLE
FlexJS path not recognized in Windows 10

### ISSUE THREAD

**Issue by gdeverlant** [BowlerHatLLC/vscode-nextgenas#100]
I don't understand why the path of FlexJS is not recognized on Windows.
The sdk is on the second partition,

![image](https://user-images.githubusercontent.com/26530975/27082175-fd65f1ce-5043-11e7-86b5-93ece3a13cf3.png)

**Comment by gdeverlant** [comment]
I even set the path in the tasks.json

![image](https://user-images.githubusercontent.com/26530975/27082410-e0e94b62-5044-11e7-9ba0-e20485202176.png)

**Comment by joshtynjala** [comment]
There must be something wrong with your SDK. Important files might be missing!

**Comment by neminovno** [comment]
Try this format: --flexHome=F:/dir/dir
Set in (CTRL+SHIFT+P then) User Settings:
"nextgenas.sdk.editor": "F:/dir/dir",

**Comment by joshtynjala** [comment]
If you download FlexJS 0.8.0 with the Flex SDK Installer, make sure to get the "release branch" version.

**Comment by neminovno** [comment]
@joshtynjala There is no 0.8.0 in Flex SDK Installer (?)
![image](https://user-images.githubusercontent.com/1468887/27083620-7111145a-5049-11e7-8988-4e174486701a.png)

**Comment by gdeverlant** [comment]
SDK Installer doesn't work with errors

![image](https://user-images.githubusercontent.com/26530975/27083794-fd292f86-5049-11e7-9eb4-cec2cfa0ac56.png)

**Comment by neminovno** [comment]
@gdeverlant What the log says?

**Comment by gdeverlant** [comment]
I've before downloaded manually from this link https://github.com/apache/flex-asjs/releases the 0.8.0-rc1

**Comment by neminovno** [comment]
Well I just tried same thing, a got another error: Error #1000
![image](https://user-images.githubusercontent.com/1468887/27084160-23d9061e-504b-11e7-9196-c67b0122e151.png)

Log end:
...
Falcon and FalconJX installed in F:\test-Apache-flexJs-install-070
Downloading Adobe AIR Runtime Kit for Windows from: http://airdownload.adobe.com/air/win/download/25.0//AdobeAIRSDK.zip
Validating download: F:\test-Apache-flexJs-install-070/in/AdobeAIRSDK.zip
Uncompressing: F:\test-Apache-flexJs-install-070/in/AdobeAIRSDK.zip
Error #1000

It is probably cause latest AIR is much larger due to 64bit.. How to solve this?

**Comment by gdeverlant** [comment]
It looks like only the version 21.0 is going through.

**Comment by neminovno** [comment]
From [run time errors](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/runtimeErrors.html):
Code 1000	
Message	Description
"The system is out of memory.	Flash needs more memory to compile your code than your system has available. Close some of the applications or processes running on your system."

**Comment by gdeverlant** [comment]
AIR 25
AIR 24
AIR 23
AIR 22

all of them are not working ... I didn't test the other ones but they might not work also.

**Comment by neminovno** [comment]
I have tried one from this link:
http://apacheflexbuild.cloudapp.net:8080/job/flex-asjs/lastSuccessfulBuild/
but no success in making v0.8.0 work in VSCode.

**Comment by joshtynjala** [comment]
> There is no 0.8.0 in Flex SDK Installer (?)

In the Flex SDK Installer, if you right-click and choose Show Dev Builds, it will show nightly builds, including the 0.8.0 release branch.

> I've before downloaded manually from this link https://github.com/apache/flex-asjs/releases the 0.8.0-rc1 Even if I do it manually it doesn't work

> I have tried one from this link: http://apacheflexbuild.cloudapp.net:8080/job/flex-asjs/lastSuccessfulBuild/ but no success in making v0.8.0 work in VSCode.

If you download 0.8.0 outside of the Flex SDK Installer, you need to manually run the install script. Expand the archive, go into the directory, and then run `ant -f installer.xml` using Ant.

> Well I just tried same thing, a got another error: Error #1000 How to solve this?

Currently, if you try to install AIR 25 with the Flex SDK Installer, you will get Error 1000 because Adobe made the download size significantly larger to add support for iOS bitcode, and 32-bit processes aren't able to allocate enough memory without crashing. You can install FlexJS with AIR 24 or older, or you can install manually with Ant. With FlexJS, you're probably not going to use AIR at all, so any version older than AIR 25 should be fine. I usually pick whatever the default is, which I think is AIR 23.

**Comment by gdeverlant** [comment]
For the manual process can you provide a video tutorial which explains step by step process?

**Comment by joshtynjala** [comment]
I can't certainly consider a video tutorial for that in the future. It's actually not very complicated.

First, you need to download [Apache Ant](http://ant.apache.org/bindownload.cgi).

Then, open the command line and run these commands:

```
cd d:\programming\sdks\flexjs-0.8.0
ant -f installer.xml
```

You may need to use the full path to ant.exe, if it's not in your Path environment variable. Let's say you extracted it to d:\programming\ant

```
cd d:\programming\sdks\flexjs-0.8.0
d:\programming\ant\bin\ant.exe -f installer.xml
```

**Comment by gdeverlant** [comment]
Hey it looks like now it works with AIR 24 and FlexJS 0.8.0 release branch

![image](https://user-images.githubusercontent.com/26530975/27085811-a6882392-5050-11e7-8154-aefcdcd28433.png)

Thanx for the video tutorial :D
