### ISSUE TITLE
[VSCODE FLEX JS] Error launching SWF debug session.

### ISSUE THREAD

**Issue by awais1947** [BowlerHatLLC/vscode-nextgenas#123]
Hi,

I am trying to create a sample Flex JS project by following the tutorial given on git hub

https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-FlexJS

Project compiles successfully. However, when i try to debug the project it gives error
"Error launching SWF debug session. Runtime not found for program: c:\VisualCode/Main.swf"

Thanks in advance.

Regards

**Comment by joshtynjala** [comment]
I noticed that you're trying to work on a FlexJS project, but you're launching a SWF file. That's a perfectly valid workflow, since FlexJS can target both SWF and JS, but I'm curious if that's your intention. Do you actually want to create a SWF? Or do you want a pure JS/HTML app?

If you do want to create a SWF and launch it directly (not embedded in HTML), you'll need to install the *Flash Player projector content debugger* from [Adobe Flash Player Debug Downloads](http://www.adobe.com/support/flashplayer/debug_downloads.html) and make sure that it's associated with .swf files on your system. For more information, see this tutorial: [Debug a SWF in the standalone Adobe Flash Player with Visual Studio Code](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-SWF-in-the-standalone-Adobe-Flash-Player-with-Visual-Studio-Code)

If you're actually embedding the SWF file in HTML, then you'll need to launch the HTML file instead.

If you prefer to target JS/HTML instead of Flash Player, then you don't want to launch a SWF at all. I've written tutorials about how to debug in [Chrome](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Google-Chrome) and [Firefox](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Mozilla-Firefox).

**Comment by awais1947** [comment]
Josh,

Thank you very much for your reply.

I am trying to configure JS/HTML app.

After posting my question, i watched your video on youtube. Which was uploaded on "The linux foundation". There was step by step procedure on how to setup visual code environment for FLex JS (Thanks to you). I followed the same procedure. However after setting the  workspace preferences i.e "nextgenas.sdk.editor" value to path where flex JS is installed. It gives error which states
"Failed to load project configuration option. Error checking disabled, except for single syntax problems(1,1)"

![touplaod](https://user-images.githubusercontent.com/31684529/30150720-f256a524-93c5-11e7-873c-fa16c2f78a86.jpg)

Also in video it is shown that to compile the project View -> Command palette -> Tasks : Configure Task Runner ( ActionScript - asconfig.json) (DEPRECATED)
![depriciated](https://user-images.githubusercontent.com/31684529/30151106-870e14a8-93c7-11e7-821d-aaf2fe805329.jpg)


Please note that (DEPRECATED) word is written in VS Code with configure task runner. I am using VS Code 1.14.0. After selecting this option another screen appears which says select a task runner. There are four options, by selecting any of them doesn't produce the "tasks.json" file as shown in video.
![aftertask](https://user-images.githubusercontent.com/31684529/30151162-d633050c-93c7-11e7-8323-6b4396d6c634.jpg)


Regards

**Comment by joshtynjala** [comment]
Unfortunately, this video is presents some out-of-date information. However, it may still be somewhat helpful.

> However after setting the workspace preferences i.e "nextgenas.sdk.editor" value to path where flex JS is installed. It gives error which states
"Failed to load project configuration option. Error checking disabled, except for single syntax problems(1,1)"

It's worth mentioning that most people shouldn't need to use the nextgenas.sdk.editor setting anymore, unless they're using "nightly" builds of FlexJS with new compiler changes. Generally, you should only need to [choose an SDK as described here](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Choose-an-ActionScript-SDK-for-the-current-workspace-in-Visual-Studio-Code).

I noticed that the filename of your MXML class has a typo (MyFirstFlexJSProect instead of MyFirstFlexJSPro**j**ect). I suspect that this is why you're getting that error. Can you verify that the file name matches what's specified in your asconfig.json file?

> Please note that (DEPRECATED) word is written in VS Code with configure task runner. I am using VS Code 1.14.0. After selecting this option another screen appears which says select a task runner. There are four options, by selecting any of them doesn't produce the "tasks.json" file as shown in video.

That's odd. That list should contain additional options for ActionScript. Regardless, it's not the recommended way to build your project anymore. Please take a look at [Build an ActionScript project in Visual Studio Code](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Build-an-ActionScript-project-in-Visual-Studio-Code) for the latest instructions.

**Comment by joshtynjala** [comment]
I also just noticed another mistake in your screenshot. It appears that the src directory and asconfig.json are inside the .vscode directory. These should be in the root instead.

**Comment by joshtynjala** [comment]
If the asconfig.json file is in the wrong location, that would definitely explain why you saw the wrong items with the "Tasks : Configure Task Runner ( ActionScript - asconfig.json) (DEPRECATED)" command. In the next version, I think I'll add a warning if the asconfig.json file is not found so that this is more obvious.

**Comment by awais1947** [comment]
Josh,

Thank you for your reply.

Yes, the first error was typo. Secondly, asconfig and src were not where they meant to be. Although you mentioned these in video(Apologies).

I made all the amendments you suggested and build the project according to the edited tutorial. And it worked like charm.

Thanks for all your efforts and time.

Best Regards

**Comment by joshtynjala** [comment]
Happy to help!
