### ISSUE TITLE
Task provider: detect additional asconfig.json files in sub directories

### ISSUE THREAD

**Issue by stijnvanderlaan** [BowlerHatLLC/vscode-nextgenas#138]
It would be great if it would be possible to have multiple asconfig.json configurations, for example like so:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"identifier": "build-debug",
			"type": "actionscript",
			"debug": true,
			"config": "asconfig.json",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
		{
			"identifier": "build-other-release",
			"type": "actionscript",
			"debug": false,
			"config": "path/to/other.asconfig.json",
			"group": {
				"kind": "build",
				"isDefault": false
			}
		}
	]
}
```
This would make it possible to have different input/output or different defines in one project.

**Comment by joshtynjala** [comment]
While the task provider isn't currently able to detect additional *asconfig.json* files in your workspace, you can add another task that runs *asconfigc* directly:

``` json
{
	"taskName": "build-other-release",
	"type": "process",
	"command": "asconfigc",
	"args": [
		"-p",
		"./path/to",
		"--flexHome",
		"/path/to/sdk"
	]
}
```

The `-p` or `--project` option allows you to point to any directory that contains an *asconfig.json* file. This task won't be able to detect your workspace settings, so you'll need to specify the `--flexHome` option too.

**Comment by joshtynjala** [comment]
I just tested with the latest TypeScript compiler, which provided some inspiration for the options available to *asconfigc*. In the past, the `-p` option for *tsc* only supported a directory containing *tsconfig.json*. I can see that it was updated at some point to also support the path to a custom JSON file—one that doesn't need to be named *tsconfig.json* anymore.

I opened BowlerHatLLC/asconfigc#14 to update *asconfigc* to support a custom JSON file too.

I'll also look into updating the ActionScriptTaskProvider in VSCode to optionally support the path to a custom JSON file, so that you don't need to manually create a "process" task.
