### ISSUE TITLE
Build: add option to compile with fcsh (Flex Compiler Shell), if available

### ISSUE THREAD

**Issue by kingBook** [BowlerHatLLC/vscode-nextgenas#156]

**Comment by joshtynjala** [comment]
Which SDK are you using?

**Comment by kingBook** [comment]
flex_sdk_4.6

**Comment by joshtynjala** [comment]
Can you try adding `-incremental=true` to the "additionalOptions" in your *asconfig.json* file?

``` json
{
	"compilerOptions": {
	},
	"additionalOptions": "-incremental=true",
	"files": [
	]
}
```

Does that make a difference? Thanks!

**Comment by joshtynjala** [comment]
You may need to compile more than once to see a difference.

**Comment by kingBook** [comment]
I have added.This is my project. 
_https://github.com/kingBook/baoWeiTianDianWangGuo_
You can download it and try to compile it.I tried to compile it over and over again, and it was still slow.
It doesn't detect file changes, skip the files that haven't been changed.

**Comment by joshtynjala** [comment]
It seems likely that FlashDevelop is using the Flex Compiler Shell (fcsh):

https://help.adobe.com/en_US/flex/using/WS2db454920e96a9e51e63e3d11c0bf67670-7fcd.html

This makes the compiler faster by keeping it active in memory. However, it's also not supported by all ActionScript SDKs. It's something I can look into for a future version of the extension, though.

**Comment by leefj** [comment]
when will you support "fcsh", if this is ready , I can drop FlashBuilder !

**Comment by joshtynjala** [comment]
@leefj I have some other priorities to finish for 1.0 first, but it's definitely on my list of things to investigate as soon as possible.

**Comment by leefj** [comment]
of course，I can wait , thanks !

**Comment by kingBook** [comment]
@joshtynjala Three Months Passed! I wait this function for a long time.Can you implement it a bit ahead of time please

**Comment by joshtynjala** [comment]
I did some investigation today, and I built a little prototype. I'm able to launch fcsh from VSCode, and I can make it compile incremental builds.

Due to limitations in VSCode, this feature will not be compatible with the regular "task" workflow that VSCode provides. Instead, the extension will provide a command that you can run from the Command Palette with Ctrl+Shift+P. As I understand it, you can assign a keyboard shortcut to any command in VSCode, so you have an option to make builds a little more convenient, if you prefer keyboard shortcuts.

The extension will provide another command that builds the project and launches a debug session at the same time. Since fcsh is activated by a command isntead of a task, it cannot be recognized as a preLaunchTask in *launch.json*.

Additionally, you'll need to use an SDK that actually includes fcsh. As I understand it, only the Adobe Flex SDK, the Apache Flex SDK, and the Feathers SDK include fcsh. The Adobe AIR SDK & Compiler and Apache Royale/FlexJS do not include fcsh or an equivalent.

**Comment by joshtynjala** [comment]
Unfortunately, I hit a snag with integrating FCSH. Apparently, FCSH does not work with Java 1.8 or newer. The FlashDevelop folks have previously figured this out and documented it here: http://www.flashdevelop.org/wikidocs/index.php?title=Java

To use FCSH, you need to install Java 1.6 or 1.7. The ActionScript & MXML extension for Visual Studio Code requires at least Java 1.8. With that in mind, to be able to use FCSH inside Visual Studio Code, you'd be required to install multiple versions of Java. While that's certainly possible, I'd rather not make it a requirement to use this feature.

So it looks like FCSH will not be supported for the Adobe/Apache Flex SDKs. However, I'm going to investigate ways to keep the AIR SDK & Compiler in memory. This is the newer ASC 2.0 compiler, so it's a different codebase that may not have the same issue. Jeff Ward created [ascsh](https://github.com/jcward/ascsh) to simulate the behavior of fcsh, but for the AIR SDK & Compiler. I will try to use that, if possible.

**Comment by piotrzarzycki21** [comment]
@joshtynjala in Moonshine we are using FCSH to build Flex applications. If it would not work I should not able to build project when I have installed Java 1.8 ? Am I understand above comment wrong ?

**Comment by joshtynjala** [comment]
@ piotrzarzycki21 It looks like Moonshine kills the fcsh process and then starts it fresh before every build. The issue with Java 1.8 happens only when you reuse the existing fcsh process.

On a related note, this means that Moonshine is not doing fast incremental compiles. It's doing a full compile every time.
