### ISSUE TITLE
Set nextgenas.sdk.framework per OS

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#194]
If `nextgenas.sdk.framework` is used to set SDK directory on Windows, and to continue working on same project on Mac, `nextgenas.sdk.framework` must be changed to SDK directory on Mac. Is it possible to have `nextgenas.sdk.framework` configured per OS so no change is required when switching OS for development? 
Lets say to have this option in _.vscode/settings.json_:
```
"nextgenas.sdk.framework": {
    "windows": "c:\\ApacheFlexSDK_4.15.0_AIR19",
    "mac": "/ApacheFlexSDK_4.15.0_AIR19"
}
```

**Comment by joshtynjala** [comment]
I don't think Microsoft expects *.vscode/settings.json* to be a file that's shared among multiple computers or among multiple team members. As I understand it, it's intended more for individual developers to customize for the computer that they're developing on currently. I certainly wouldn't commit this file to a repository, for instance.

While your suggested change might help somewhat for a single user switching between a couple of different computers/platforms, it won't really work all that well for a project with three or more team members because they're not guaranteed to save their SDKs in the same location.

I looked at the `typescript.sdk` setting for TypeScript, and there doesn't appear to be a way to specify multiple paths for multiple platforms. I generally try to follow how TypeScript integrates with VSCode to keep the experiences similar for developers using both languages.

With all that in mind, this is a change that I would be wary to make.
