### ISSUE TITLE
Completion: Display namespace for each particular suggestion

### ISSUE THREAD

**Issue by olafkrueger** [BowlerHatLLC/vscode-nextgenas#195]
Similar to FlashBuilder, it would be helpful and more ergonomic, if the namespace would be displayed as leading string [1][2].

Keep up the great work!!

Thanks,
Olaf

[1] FlashBuilder with leading namespace
![image](https://user-images.githubusercontent.com/14052170/38701871-56d548d2-3e9f-11e8-91f9-7c5eca04223b.png)

[2] VSCode with missing namespace
![image](https://user-images.githubusercontent.com/14052170/38701557-7bc6dbb6-3e9e-11e8-8a44-932620524690.png)

**Comment by joshtynjala** [comment]
Good suggestion! I'll try to get it into v0.12.

**Comment by olafkrueger** [comment]
Great Josh, Thank you!!!

**Comment by joshtynjala** [comment]
This post is for my future reference.

I should be able to add the following code in addDefinitionAutoCompleteMXML()

``` java
item.setLabel(prefix + IMXMLCoreConstants.colon + definition.getBaseName());
item.setSortText(definition.getBaseName());
```

This will add the prefixes, and similar base class names will be sorted together still.

Ideally, this should be combined with #186 so that better namespace prefixes will be generated for MXML namespace URIs that aren't hard-coded. Right now, it defaults to something like `ns1`. Apache Royale has a lot of ns1 prefixes right now, which isn't much of an improvement over no prefixes at all.
