### ISSUE TITLE
AS and MXML files not in source-path folders should not be checked for errors

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-nextgenas#21]
I'm not sure if this a question or a feature request.

Right now, the extension is analyzing all files in any folder of my project with the following extensions: .as, .jsx, .mxml and I'm getting a lot of irrelevant errors and problems.

Ideally the extension could analyze dependencies and only show errors for dependency files. At the very least, it would be very helpful to be able to specify source folder(s) and ignore files in other folders. (i.e. only files inside "src") I'd also like to exclude jsx files because those are Adobe ExtendScript files. I'm guessing it's analyzing those because it thinks they are React files?

**Comment by joshtynjala** [comment]
I don't tell the NextGenAS extension to look for jsx files. That may be the built-in JavaScript extension. And yes, I think it's because that extension is used for React with JSX.

I think I tell it to check for errors in opened as and mxml files, even if they aren't in the source path. Only opened files, though. If they're not in the source path, but not open, there should be no errors. The errors should also clear once a file is closed, if it's not in the source path.

**Comment by Harbs** [comment]
FWIW, it looks like it only checks non-project files if they are open, so this seems like a non-issue.
