### ISSUE TITLE
AIR mobile packaging: package different for different AIR version

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#230]
[Here](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/asconfig.json#target-1) in Wiki it says:

> The package target for Android. When omitted, defaults to apk-captive-runtime for release builds. Debug builds always use apk-debug, even when this field is not omitted.
> 
> ```
> "airOptions": {
> 	"android": {
> 		"target": "apk-profile"
> 	}
> }
> ```
> 

Without using that option, after trying Android release builds with two AIR versions, here is what happens:

- When using AIR 3.1 it looks like it doesn't package AIR. That .apk installed on device just makes app start and close.
- When using AIR 19.0 it does packages captive runtime, and app works properly on device. And in output it does say:  "NOTE: The application has been packaged with a captive runtime."
 

Is it bug or there is option to set mobile package type when using older AIR versions? Isn't captive runtime only and default mobile package option but after AIR 2x some version?

Also, it looks like there is some string leftover, see "test" in output:

> C:\dev\vsc-extensions\test3\bin\MyApp.swf (623 bytes)
> Adobe AIR code signing password:
> testNOTE: The application has been packaged with a captive runtime.
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by joshtynjala** [comment]
> When using AIR 3.1 it looks like it doesn't package AIR. That .apk installed on device just makes app start and close.

According to [this page](https://www.adobe.com/devnet/articles/flashplayer-air-feature-list.html), Adobe AIR has been able to create captive runtime apps for Android since AIR 3.7.

Adobe hasn't updated the shared AIR runtime for Android beyond AIR 25.

With this in mind, I think apk-captive-runtime is a good default, even if it breaks AIR 3.6 and older.

> there is option to set mobile package type when using older AIR versions?

You actually quoted the snippet that shows you how. You can set the `target` to any supported value, including `apk`:

``` json
"airOptions": {
	"android": {
		"target": "apk"
	}
}
```
