### ISSUE TITLE
-inline causing bytecode errors in VSCode

### ISSUE THREAD

**Issue by hydroper** [BowlerHatLLC/vscode-nextgenas#245]
My VSCode project gets 87 problems if I pass the `-inline` flag in `[asconfig.json].additionalOptions`. 
Actually, I've a lot of methods to be inlined, and only few of them aren't returning a value directly.

It just had one problem, the air-config.xml unable to open, which is related to AIR_SDK. Actually I'm getting a lot of `Generated byte code contains an operand stack underflow. (1, 1)`, but the compiler doesn't trace these errors.

**Comment by hydroper** [comment]
Strangely I'm able to strip one error by removing the `[Inline]` meta-data from my `ErrorHandler.as#push()` method.

### Before

![image](https://user-images.githubusercontent.com/15965072/43085313-105f7d24-8e71-11e8-9c05-7855414684fb.png)

### Later

![image](https://user-images.githubusercontent.com/15965072/43085371-4158c0e8-8e71-11e8-8e12-809b0702ad3f.png)

**Comment by joshtynjala** [comment]
The code intelligence in VSCode is based on the Apache Royale compiler (even for non-Royale projects, since it's designed to work with any framework). The Royale compiler was forked from the ASC 2.0 compiler in Adobe's AIR SDK quite a while back. If I remember correctly, the `-inline` compiler option and `[Inline]` metadata were still **very** unstable at the time (to be honest, I'm not completely convinced that inlining is even completely stable in the AIR SDK today). It's very likely that any fixes that Adobe made to the compiler after the fork were never contributed to Royale.

I would avoid using `-inline` in VSCode during development. Remove the `-inline` option until you want to do a release build.
