### ISSUE TITLE
[Question] Is debugging of linked libs (swc) and modules (swf) already supported?

### ISSUE THREAD

**Issue by olafkrueger** [BowlerHatLLC/vscode-nextgenas#248]
Hi,
I am trying to get the debugger stop at linked libs or loaded modules. 
Is this basically already supported and if so, is there an example of what is needed to get it work?

Thanks!
Olaf

**Comment by joshtynjala** [comment]
I think that SWCs will work, as long as the original source code is at the same location in the file system as when the SWC was compiled. You probably need to ensure that the SWC is compiled with the `debug` compiler option set to true.

I have never tried debugging SWF modules loaded at runtime. If it works automatically, then it probably has the same requirements.The SWF should be a debug build, and the source files should exist at their original locations.

**Comment by olafkrueger** [comment]
Thanks, Josh!
Does that mean that there is no need to define the source path wherever?
(E.g. by setting  the "source-path" option)

**Comment by olafkrueger** [comment]
I'll give it a try tomorrow...!

**Comment by olafkruger** [comment]
@joshtynjala 

Today I was able to debug linked libs (swc)!:

Basically, as you said, it works out of the box without any additional configurations.
But it seems to me that we have to use a workspace in order to get it work, is that right?
I guess that I accidently launched my app without using the related workspace yesterday.
Moreover, I am not sure if some breakpoints sporadically doesn't work. I'll observe this.

Regarding modules (swf):
Same here, after defining a workspace for my test app which just contains a moduleloader and a module, it just works out of the box:

ModuleDebugTest.code-workspace:
```
{
	"folders": [
		{
			"path": "apps\\testing\\shell"
		},
		{
			"path": "moduleloader"
		}
	]
}
```


BTW:
I often stumble over those "unverified breakpoints" [1].
After the app is launched, the breakpoint switches from red to this unverified one.
But it seems to me that the breakpoint still works... do you know something about this?

Thank you!!
Olaf


[1]
![image](https://user-images.githubusercontent.com/38468124/43512489-8107d6b4-957b-11e8-8143-54001fd4cc57.png)

**Comment by joshtynjala** [comment]
> But it seems to me that we have to use a workspace in order to get it work, is that right?

Do you mean that you need to create a workspace that includes **both** the app and the SWC projects as root folders? I wouldn't expect that to be necessary.

> I often stumble over those "unverified breakpoints"

Do you see unverified breakpoints in all projects, or is it in modules only?

**Comment by olafkrueger** [comment]
> Do you mean that you need to create a workspace that includes both the app and the SWC projects as root folders?

What do you mean by "root folders"?
My understanding of the workspace file is that it is just an array of folders at the same level?
I probably miss something here...

> Do you see unverified breakpoints in all projects, or is it in modules only?

If I remember it correctly I saw this unverified breakpoints only in included libs or modules.
I'll check this out tomorrow!

**Comment by olafkruger** [comment]
> Do you see unverified breakpoints in all projects, or is it in modules only?

I found this:
- When using a workspace (single-root or multi-root), every breakpoint is always unverified after the debugger is started
- When opening just the folder where the main moduleloader app lives, it seems to me that always only the last breakpoint is ok (red), all others all unverified
- Stting breakpoints at runtime always works (remains red)
- Reapplying breakpoints at runtime also works (all breakpoints red) [1]

It turns out to me, that if theres no way to get a breakpoint red during runtime, it definately won't work!
But vice versa an unverified breakpoint works as long as it could be reapplied.
So, basically there's no need to reapply breakpoints in order to get it work.


>Do you mean that you need to create a workspace that includes both the app and the SWC projects as root folders?

Today, the debugging of a loaded module works for me indeed without using a workspace.
Just opening the folder of the "moduleloader app" is enough.
That is a bit weird for me because I am pretty sure that yesterday debugging doesn't worked for me until I've added the resources of the libs/modules to the workspace (multi-root).

Moreover, the debugging of linked libs (swc) does not work today... I will investigate here a bit more.
I probably messed up things here while testing.

However, I guess, as you said, there's probably no need to create a multi-root workspace in order to get the debugging of linked libs/modules work.

[1] Reappling breakpoints the simple way:
![image](https://user-images.githubusercontent.com/38468124/43573744-c2b3b2f0-9642-11e8-904c-b6dd708fc099.png)

**Comment by olafkruger** [comment]
Mhh... I just recompiled the app and all linked libs/modules (without changing any code or the location at the file system) and debugging works like a charm for all linked libs and modules.
I'll observe this... ;-)

**Comment by olafkruger** [comment]
I found that I have to use the commands "Reload Window" or "Restart AS/MXML server" in order to detect changes of a lib or a module which are living in other VSCode windows/instances.
Without this e.g. the code completition doesn't know about the changes in the code.
I guess this will be resolved with multi-root workspace support? ;-)

However, I really looking forward to the next release!

**Comment by joshtynjala** [comment]
If a SWC file on the library-path is changed, I don't think that it will be detected automatically right now. Can you open a separate issue for that?

**Comment by olafkruger** [comment]
See 
- #250 (Detect changes automatically)
- #251 (Unverified breakpoints)

**Comment by olafkruger** [comment]
@joshtynjala 
This issue could be closed because the original question is answered!
Thanks for your help! ;-)

**Comment by olafkrueger** [comment]
Ahh.. I wasn't able to close it because I was logged in with the wrong user.
Closed it by myself now ;-)
