### ISSUE TITLE
Executing task: asconfigc --debug=false --flexHome failure

### ISSUE THREAD

**Issue by yonnyzohar** [BowlerHatLLC/vscode-nextgenas#262]
This is a really noob question - i'm stuck on the first step.
I've defined an sdk path, created the asconfig file and when i compile i get the following error:

execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

I've tried with other sdk's that the system picked up on it own - same result.
what am i doing wrong?

by the way, i'm on a mac..

**Comment by joshtynjala** [comment]
> execvp(3) failed.: No such file or directory

As I understand it, this error means that it's failing to run an executable. Either it cannot find the executable, or it doesn't have permission to access the executable.

However, this seems like a bigger issue:

> --flexHome

It should be using `--sdk` instead of `--flexHome`. I made that change a long time ago, so it seems that you have a **very** old version of something installed. Which version of the extension do you have installed? Which version of Visual Studio Code?

**Comment by yonnyzohar** [comment]
I installed your plugin today, vscode is from several months ago (not currently at my computer...)

**Comment by joshtynjala** [comment]
If you haven't been keeping VSCode up to date, you may not have gotten the newest version of the AS3 & MXML extension. While I can't think of any reason why older versions would be broken, I think that it's important that you make sure that everything is updated before we look at anything else.

These are the newest versions right now as I'm posting this:

VSCode: 1.26.1
AS3 & MXML: 0.13.0

**Comment by yonnyzohar** [comment]
It worked! i updated vscode, uninstalled and re-installed your plugin and got past the error. seems to be working! thanks!
