### ISSUE TITLE
Can't run AIR project

### ISSUE THREAD

**Issue by yonnyzohar** [BowlerHatLLC/vscode-nextgenas#263]
I'm trying to run an Air app, but keep crashing whenever i try to access an air Class. 

VerifyError: Error #1014: Class flash.filesystem::File could not be found.

my launch.json:

```
"version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch AIR mobile",
            "profile": "mobileDevice",
            "screensize": "iPhoneRetina",
            "screenDPI": 326,
            "versionPlatform": "IOS",
            "program": "${workspaceRoot}/bin/Game.swf"
        }
    ]
```

/////
appconfig.json
```
{
	"config": "air",
	"compilerOptions": {
		"output": "bin/Game.swf",
		 "library-path": ["libs", "bin" ]
	},
	"application": "src/Game-app.xml",
	"files": [
		"src/Main.as"
    ],
    "airOptions": {
		"mac": {
			"output": "Game.app"
		}
	}
}
```

any thoughts?

**Comment by joshtynjala** [comment]
It's trying to launch in Flash Player instead of AIR because you set the `program` field in *launch.json* to a *.swf* file. To launch an AIR app, the `program` field should point to your *-app.xml* file.

However, don't change it to your *-app.xml file. The AS3 & MXML extension is designed to auto-detect the program to launch based on the compiler options of *asconfig.json*.  Remove this line entirely, and it should work correctly:

> "program": "${workspaceRoot}/bin/Game.swf"

**Comment by yonnyzohar** [comment]
Thanks for your reply! the change worked! however, now my app launches up and closes instantly...

**Comment by joshtynjala** [comment]
Do you see anything in the debug console when it launches?

Without seeing an answer, I'd guess that you need to set the AIR version in your *-app.xml* file to the correct version for your SDK.

**Comment by yonnyzohar** [comment]
BINGO! Thank you! it works!
