### ISSUE TITLE
JS project loads Royale libs

### ISSUE THREAD

**Issue by taorepoara** [BowlerHatLLC/vscode-nextgenas#269]
The JS project, like [the one in the wiki](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-JavaScript-and-HTML), always load the Royale libs. 
```
MXMLJSC
+royalelib=...
```

Those libs can interfer with the Javascript project classes.

**Comment by joshtynjala** [comment]
When you see the `+royalelib` command line option, that does not necessarily indicate that the Royale framework is being used.

When you specify `"config": "js"` in *asconfig.json*, it will load *frameworks/js-config.xml* from your Royale SDK. This configuration should load only JS globals and not the entire Royale framework.

**Comment by taorepoara** [comment]
The problem is that I have a building error using this config on a project but the project builds perfectly using the asjsc command with the same params.

**Comment by joshtynjala** [comment]
Can you share a simple project that will demonstrate the errors?

**Comment by taorepoara** [comment]
I'm creating lib base on the playerglobal classes in order to help to transpile existing AS3 project to JS : [playerglobal.js](https://gitlab.com/lenra/playerglobal.js/). The build of the swc file works perfectly with the asconfig.json file but I've made a project to test the classes implementation and this project have a NullPointerException at the end. 

[PlayerglobalTester.zip](https://github.com/BowlerHatLLC/vscode-nextgenas/files/2364589/PlayerglobalTester.zip)

Thank you for your help.

**Comment by joshtynjala** [comment]
I see that your playerglobal.js project includes implementations of some built-in language classes like `Boolean`, `Array`, and `Date`. You should remove those classes because they will definitely cause conflicts. In fact, this is probably why you're getting an exception.

Basically, anything that isn't in the *flash*, *flashx*, or *fr* packages under *source/main/actionscript*  should be removed from playerglobal.js because they're already provided by JavaScript. Royale knows how to handle them automatically.

**Comment by joshtynjala** [comment]
Was this the NullPointerException that you were seeing?

> using source file: c:\Users\josht\Desktop\PlayerglobalTester\bin\js-debug\Main.js
Internal error: java.lang.NullPointerException org.apache.royale.compiler.internal.graph.GoogDepsWriter.generateDeps(GoogDepsWriter.java:214)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.publish(MXMLRoyalePublisher.java:426)org.apache.royale.compiler.clients.MXMLJSCNative.compile(MXMLJSCNative.java:376)org.apache.royale.compiler.clients.MXMLJSCNative._mainNoExit(MXMLJSCNative.java:234)org.apache.royale.compiler.clients.MXMLJSCNative.mainNoExit(MXMLJSCNative.java:191)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:401)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:300)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:259)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:241)

**Comment by taorepoara** [comment]
Ok, thank you for the advice.

Yes, exactly.

**Comment by joshtynjala** [comment]
I'm making a few commits to the Royale compiler that should help clear up these exceptions. You'll be able to try a nightly build soon that I think will work better.

**Comment by joshtynjala** [comment]
By the way, I found that it sometimes helps to delete your *bin* directory when you get this exception.

**Comment by joshtynjala** [comment]
After there's a nightly build of Royale with my new compiler changes, you should change your *asconfig.json* for playerglobal.js library to look like this:

```
{
	"type": "lib",
	"config": "js",
	"compilerOptions": {
        "targets": [
            "SWF",
            "JS"
        ],
        "include-sources": [
            "sources/main/actionscript",
            "sources/main/javascript"
        ],
        "output": "bin/playerglobalJS.swc"
    }
}
```

It's not strictly required, but at least when you're working on that project, all of the Royale UI components will be hidden from code intelligence.

Previously building a SWC with `"config": "js"` was failing, but that was one of the bugs that I just fixed in the compiler.
