### ISSUE TITLE
Persistent "You must configure a SDK..." dialog in non-Actionscript workspaces

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-nextgenas#284]
Steps to reproduce:

1- Create a new workspace for other non-Actionscript languages (javascript, python, etc.)
2- "You must configure a SDK..." dialog appears every time if no SDK is selected.

Description:

I work in other languages with VS Code, for example Python. And every time I open my Python workspace I get this dialog. There's no point on showing the SDK option in the bottom status bar either.

Also, the Actionscript/MXML language server initializes.

**Comment by joshtynjala** [comment]
The language server generally shouldn't initialize unless *asconfig.json* is present, if you open an *.as* or *.mxml* file, or if you run one of the commands provided by the extension.

Is the **ActionScript Source Path** view open? I think that could cause the extension to initialize too. If you collapse it, that might prevent the extension from initializing. Last time I checked, I couldn't find a way to hide it by default, but I'll look again. Maybe something new has been added since I first introduced that feature.

It's worth mentioning that I personally make it a habit of disabling any extensions that I don't need in a particular workspace. I have some Java projects that I work on, and I always disable my extensions related to ActionScript and JavaScript in these workspaces. Similarly, I disable the Java extension in other workspaces where I'm using another language. It just seems like *any* extra extensions in a workspace always add little annoyances, not just the AS3 & MXML one. It's a little annoying, but it seems to give me a better experience in all languages.

**Comment by angelhdz** [comment]
> The extension generally shouldn't initialize unless _asconfig.json_ is present, if you open an _.as_ or _.mxml_ file, or if you run one of the commands provided by the extension.
> 
> Is the **ActionScript Source Path** view open? I think that could cause the extension to initialize too. If you collapse it, that might prevent the extension from initializing. Last time I checked, I couldn't find a way to hide it by default, but I'll look again. Maybe something new has been added since I first introduced that feature.
> 
> It's worth mentioning that I personally make it a habit of disabling any extensions that I don't need in a particular workspace. I have some Java projects that I work on, and I always disable my extensions related to ActionScript and JavaScript in these workspaces. Similarly, I disable the Java extension in other workspaces where I'm using another language. It just seems like _any_ extra extensions in a workspace always add little annoyances, not just the AS3 & MXML one. It's a little annoying, but it seems to give me a better experience in all languages.

I don't have anything related to Actionscript/MXML on my Python workspace. Each project has their own launch.json file and everything is Python related configurations.

Didn't occurred to me that I could disable extensions per-workspace? That's awesome. I will follow your workflow and it will surely solve this kind of issues in the future.

Thank you Josh! As always, I appreciate your time, kindness and information.

**Comment by joshtynjala** [comment]
I'm reopening until I'm done investigating whether I have more control over when the ActionScript Source Path view in the Explorer is opened.

**Comment by joshtynjala** [comment]
If you click on the gear icon ⚙ next to the extension, you can choose **Disable (Workspace)**.

**Comment by joshtynjala** [comment]
With this commit, the ActionScript Source Path view is now visible only when an *.as* or an *.mxml* file is open in the editor. I have confirmed that the extension will not initialize in workspaces for other languages, even if it hasn't been disabled.

**Comment by angelhdz** [comment]
I just made an Indie Developer pledge on your Patreon. 

Unfortunately can't do it recurrent (I'm not having income as developer at this time), but every time I can  I will subscribe and pledge.

:) I appreciate your hard work. Finding committed people like you is hard.

**Comment by angelhdz** [comment]
If I understood correctly, the money is hold until 1st of next month, so my today's pledge will be collected on November the 1st. After that, I can cancel the membership. Is this correct?
