### ISSUE TITLE
asconfig suggestion

### ISSUE THREAD

**Issue by JimmyGot** [BowlerHatLLC/vscode-nextgenas#38]
Wouldn't it make sense to move the asconfig.json file to the .vscode folder to have all settings in one place? Just looked for this file in a large project and it gets listed at the end while the .vscode folder is on top.

**Comment by joshtynjala** [comment]
Your idea is coming from the right place, but there are reasons this file gets special treatment. TypeScript's tsconfig.json does not go into the .vscode/ directory either. These files are also used by compilers, and they aren't considered specific to VSCode. However, tasks.json, launch.json, and settings.json are only intended for VSCode and nothing else. Additionally, a developer might omit the .vscode/ directory from their repo because it contains settings specific to their local machine, but asconfig.json contains compiler options that will be the same everywhere.
