### ISSUE TITLE
Apache license compatibility issue

### ISSUE THREAD

**Issue by justinmclean** [BowlerHatLLC/vscode-nextgenas#58]
Not a big issue but noticed a couple of license issue that would be nice to clear up. Up to you if you want to do anything about this.
 
I see ou have included in LICENSE an EPL license, this is regarded as a category B license. [1] I assume this is just a dependancy and no EPL licensed source code is included in the repo?

The JSON license is regarded as category X [2] and can't be included or have a dependancy on. What code or dependancy is JSON licensed?

Policy wise at the ASF then no need to list copyrights in NOTICE files (other than in certain situations) as it impacts on downstream projects. You may want to consider removing them if you intend on bringing to code to Apache and/or have an ASF project use you code.

1. https://www.apache.org/legal/resolved#category-b
2. https://www.apache.org/legal/resolved#category-x

**Comment by joshtynjala** [comment]
1. Correct, the EPL licensed libraries are dependencies. Their source code is not included in vscode-nextgenas.

2. It appears that the org.json library is a dependency of the JSON schema validator library [everit-org/json-schema](https://github.com/everit-org/json-schema). I tried to find a GSON based validator since I'm using GSON elsewhere, but I had no luck.

> Policy wise at the ASF then no need to list copyrights in NOTICE files

If I'm parsing this correctly, I think you're saying that dependencies don't need to be included in NOTICE files unless their source code is included. Is that correct?

**Comment by justinmclean** [comment]
Yes there no need to list dependancies only what is included/bundled in the source. But also NOTICE is only for required notices not to list copyrights of included software (unless it's the case they have been relocated from header files.)

**Comment by joshtynjala** [comment]
@justinmclean Thank you! Good to know.
