### ISSUE TITLE
wiki: mention WindowedApplication when targeting Apache Flex SDK desktop

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-nextgenas#62]
For desktop builds WindowedApplication is used.
Maybe this line is missing in [Create a project that targets the classic Apache Flex SDK](https://github.com/BowlerHatLLC/vscode-nextgenas/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-the-classic-Apache-Flex-SDK) at the end of 7. step:
"An Adobe AIR project that targets desktop should set `WindowedApplication `instead `Application`."

**Comment by joshtynjala** [comment]
Will the project still compile and run if you use Application instead of WindowedApplication with AIR? I would expect that to be allowed, but it's been a while since I last tried. I ask because this page is supposed to be focused more on configuring the project and workspace settings. The sample "Hello World" code Flex MXML is probably the least important detail there.

That said, if using Application with AIR results in compiler or runtime errors, then I agree that it would be better to make it note about WindowedApplication. If it runs fine, I'd rather keep these instructions simpler.

**Comment by neminovno** [comment]
After quick test it looks answer is no.
Just tried new Flex project in FB 4.6 for desktop with Adobe Flex 4.6.0 SDK, then changed WindowedApplication to Application, and results are; no problems reported, compilation works, but when run - no initial window is visible. After quick check that is probably because to that `WindowedApplication ` implements `IWindow` and it [returns NativeWindow](https://github.com/apache/flex-sdk/blob/develop/frameworks/projects/airspark/src/spark/components/WindowedApplication.as#L1258-L1276) for app.

**Comment by joshtynjala** [comment]
Okay, I'll add a note.

I actually recall now that WindowedApplication has some special code that sets the native window's visible property to true manually because the default template for an AIR application descriptor has it set to false, for some strange reason. This is probably why you don't see the native window. Application doesn't have this special logic.
